[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get -yqq install libssl-dev:$CROSS_DEB_ARCH pkg-config:$CROSS_DEB_ARCH protobuf-compiler:$CROSS_DEB_ARCH"
]