name: "Build"

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "sinatra"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "lambda-gtfsrs"
  CONFIG_DIRECTORY: "./terraform"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: |
          npm install --no-bin-links
          npm run build
          cp -r node_modules dist/node_modules
          (cd dist && zip -r ../lambda-gtfsrt.zip .)
      - uses: actions/upload-artifact@v4
        with:
          name: lambda-gtfsrt
          path: ./lambda-gtfsrt.zip
  upload-s3:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/download-artifact@v4
        with:
          name: lambda-gtfsrt
          path: ./
      - run: aws s3 cp lambda-gtfsrt.zip s3://${{ vars.AWS_LAMBDA_BUCKET }}
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs:
      - upload-s3
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: lambda-gtfsrt
          path: ./terraform
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
          