name: Test
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: arduino/setup-protoc@v3
    - name: Setup rust
      run: |-
        rustup install 1.88.0
        rustup override set 1.88.0
    - name: Build
      run: cargo build --manifest-path core/Cargo.toml
    - name: Test
      run: cargo test --verbose --manifest-path core/Cargo.toml
